export const categories = [
  { id: "1", name: "Web Development", icon: "🌐", count: 42 },
  { id: "2", name: "Mobile Development", icon: "📱", count: 28 },
  { id: "3", name: "Data Science", icon: "📊", count: 35 },
  { id: "4", name: "Design", icon: "🎨", count: 22 },
  { id: "5", name: "Business", icon: "💼", count: 18 },
  { id: "6", name: "AI & Machine Learning", icon: "🤖", count: 30 },
];

export const courses = [
  {
    id: "1",
    title: "React Mastery: From Zero to Hero",
    description: "Pelajari React dari dasar hingga advanced. Build real-world projects dengan hooks, context, dan Redux.",
    instructor: "Sarah Chen",
    instructorAvatar: "",
    price: 299000,
    rating: 4.8,
    reviewCount: 1240,
    studentCount: 5680,
    level: "Beginner" as const,
    category: "Web Development",
    thumbnail: "",
    duration: "32 jam",
    lessonCount: 180,
    featured: true,
    badges: ["Best Seller", "Hot"],
  },
  {
    id: "2",
    title: "Python untuk Data Science",
    description: "Kuasai Python, Pandas, NumPy, dan Matplotlib untuk analisis data profesional.",
    instructor: "Budi Santoso",
    instructorAvatar: "",
    price: 349000,
    rating: 4.9,
    reviewCount: 890,
    studentCount: 4200,
    level: "Intermediate" as const,
    category: "Data Science",
    thumbnail: "",
    duration: "28 jam",
    lessonCount: 150,
    featured: true,
    badges: ["Top Rated"],
  },
  {
    id: "3",
    title: "UI/UX Design Fundamentals",
    description: "Belajar prinsip desain, Figma, user research, dan prototyping untuk membuat produk yang user-friendly.",
    instructor: "Anika Putri",
    instructorAvatar: "",
    price: 249000,
    rating: 4.7,
    reviewCount: 560,
    studentCount: 3100,
    level: "Beginner" as const,
    category: "Design",
    thumbnail: "",
    duration: "20 jam",
    lessonCount: 95,
    featured: true,
    badges: ["New"],
  },
  {
    id: "4",
    title: "Flutter Mobile App Development",
    description: "Build beautiful cross-platform mobile apps dengan Flutter dan Dart.",
    instructor: "Riko Firmansyah",
    instructorAvatar: "",
    price: 399000,
    rating: 4.6,
    reviewCount: 420,
    studentCount: 2800,
    level: "Intermediate" as const,
    category: "Mobile Development",
    thumbnail: "",
    duration: "36 jam",
    lessonCount: 200,
    featured: false,
    badges: [],
  },
  {
    id: "5",
    title: "Machine Learning with TensorFlow",
    description: "Pelajari machine learning dari teori hingga implementasi dengan TensorFlow dan Keras.",
    instructor: "Dr. Hana Wijaya",
    instructorAvatar: "",
    price: 499000,
    rating: 4.9,
    reviewCount: 780,
    studentCount: 3600,
    level: "Advanced" as const,
    category: "AI & Machine Learning",
    thumbnail: "",
    duration: "40 jam",
    lessonCount: 220,
    featured: true,
    badges: ["Best Seller", "Top Rated"],
  },
  {
    id: "6",
    title: "Digital Marketing Mastery",
    description: "Strategi marketing digital: SEO, social media, content marketing, dan Google Ads.",
    instructor: "Maya Sari",
    instructorAvatar: "",
    price: 199000,
    rating: 4.5,
    reviewCount: 340,
    studentCount: 2100,
    level: "Beginner" as const,
    category: "Business",
    thumbnail: "",
    duration: "18 jam",
    lessonCount: 85,
    featured: false,
    badges: ["New"],
  },
];

export const learningPaths = [
  {
    id: "1",
    title: "Full-Stack Web Developer",
    description: "Jadi full-stack developer dalam 6 bulan. Dari HTML/CSS hingga React, Node.js, dan database.",
    courseCount: 5,
    duration: "120 jam",
    studentCount: 2400,
    badge: "🏆 Full-Stack Champion",
    color: "from-fun-purple to-fun-blue",
    courses: ["1", "4"],
  },
  {
    id: "2",
    title: "Data Scientist Path",
    description: "Kuasai data science dari Python basics hingga machine learning dan deep learning.",
    courseCount: 4,
    duration: "96 jam",
    studentCount: 1800,
    badge: "🧠 Data Wizard",
    color: "from-fun-green to-fun-blue",
    courses: ["2", "5"],
  },
  {
    id: "3",
    title: "Product Designer",
    description: "Belajar design thinking, UI/UX, prototyping, dan design systems.",
    courseCount: 3,
    duration: "60 jam",
    studentCount: 1200,
    badge: "🎨 Design Master",
    color: "from-fun-pink to-fun-orange",
    courses: ["3"],
  },
];

export const leaderboard = [
  { rank: 1, name: "Andi Pratama", points: 12500, badges: 24, avatar: "", level: 15 },
  { rank: 2, name: "Siti Nurhaliza", points: 11200, badges: 21, avatar: "", level: 14 },
  { rank: 3, name: "Dimas Raharjo", points: 10800, badges: 20, avatar: "", level: 13 },
  { rank: 4, name: "Putri Ayu", points: 9500, badges: 18, avatar: "", level: 12 },
  { rank: 5, name: "Rizky Fauzan", points: 8900, badges: 16, avatar: "", level: 11 },
];

export const badges = [
  { id: "1", name: "First Step", icon: "👶", description: "Selesaikan kursus pertamamu", criteria: "complete_1_course", earned: true },
  { id: "2", name: "Fast Learner", icon: "⚡", description: "Selesaikan 5 kursus", criteria: "complete_5_courses", earned: true },
  { id: "3", name: "Knowledge Seeker", icon: "📚", description: "Selesaikan 10 kursus", criteria: "complete_10_courses", earned: false },
  { id: "4", name: "Quiz Master", icon: "🎯", description: "Dapat nilai sempurna di quiz", criteria: "perfect_quiz", earned: true },
  { id: "5", name: "Path Finder", icon: "🗺️", description: "Selesaikan learning path pertama", criteria: "complete_1_path", earned: false },
  { id: "6", name: "Social Butterfly", icon: "🦋", description: "Tulis 10 review", criteria: "write_10_reviews", earned: false },
  { id: "7", name: "Streak Master", icon: "🔥", description: "Belajar 30 hari berturut-turut", criteria: "30_day_streak", earned: false },
  { id: "8", name: "Top Student", icon: "🏅", description: "Masuk top 10 leaderboard", criteria: "top_10_leaderboard", earned: false },
];

export const formatPrice = (price: number) => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(price);
};
