import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        // Academic Architecture typography
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        // Aliases for backward compat
        heading: ['Manrope', 'sans-serif'],
      },
      colors: {
        // shadcn/ui CSS-variable-based colors (keep for component compatibility)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // --- Academic Architecture flat color tokens (from reference templates) ---
        "on-background": "#191b23",
        "on-tertiary-container": "#ffc89e",
        "surface-tint": "#0c56d0",
        "on-primary-container": "#c4d2ff",
        "secondary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-variant": "#e1e2ec",
        "inverse-surface": "#2e3038",
        "on-secondary": "#ffffff",
        "on-surface": "#191b23",
        "surface-container-low": "#f3f3fd",
        "surface-container": "#ededf8",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#415382",
        "surface-container-high": "#e7e7f2",
        "surface-container-highest": "#e1e2ec",
        "inverse-primary": "#b2c5ff",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001848",
        "on-surface-variant": "#434654",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-tertiary-fixed": "#2f1500",
        "background-academic": "#faf8ff",
        "outline-variant": "#c3c6d6",
        "outline": "#737685",
        "on-primary-fixed-variant": "#0040a2",
        "tertiary-container": "#8b4a00",
        "on-secondary-fixed-variant": "#344573",
        "on-error-container": "#93000a",
        "surface-dim": "#d9d9e4",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#021945",
        "inverse-on-surface": "#f0f0fb",
        "tertiary-fixed": "#ffdcc3",
        "primary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#b4c5fb",
        "on-primary": "#ffffff",
        "tertiary": "#693600",
        "secondary-container": "#b6c8fe",
        "primary-container": "#0052cc",
        "error": "#ba1a1a",
        // fun- aliases kept for backward compat
        fun: {
          blue: "hsl(var(--fun-blue))",
          pink: "hsl(var(--fun-pink))",
          yellow: "hsl(var(--fun-yellow))",
          green: "hsl(var(--fun-green))",
          orange: "hsl(var(--fun-orange))",
          purple: "hsl(var(--fun-purple))",
        },
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        md: "0.75rem",
        sm: "0.375rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
